services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-app:/usr/src/app  # Montar el directorio local en el contenedor
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #   depends_on:
  #     - backend

networks:
  app-network:
    driver: bridge

volumes:
  frontend-app:
    name: frontend-app
    driver_opts:
      device: '/home/larrain/Desktop/transcendence/frontend/pong-app'
      o: bind
      type: none 
  postgres-data:
