global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: 'https://otxobot.grafana.net/a/cloud-home-app'
    basic_auth:
      username: 'otxobot
      password: '8c2d3f59-49c8-42bd-aa2d-7a76372b459d'